"""fix plus_one_of_id foreign key to reference guests

Revision ID: 70e6186c5a09
Revises: 54c8e98ab9ff
Create Date: 2026-02-07 12:22:10.313562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70e6186c5a09"
down_revision = "54c8e98ab9ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guests", sa.Column("bring_a_plus_one_id", sa.Uuid(), nullable=True))
    op.drop_constraint(op.f("guests_plus_one_of_id_fkey"), "guests", type_="foreignkey")
    op.create_foreign_key(
        None, "guests", "guests", ["bring_a_plus_one_id"], ["uuid"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "guests", "guests", ["plus_one_of_id"], ["uuid"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "guests", type_="foreignkey")
    op.drop_constraint(None, "guests", type_="foreignkey")
    op.create_foreign_key(
        op.f("guests_plus_one_of_id_fkey"),
        "guests",
        "users",
        ["plus_one_of_id"],
        ["uuid"],
        ondelete="SET NULL",
    )
    op.drop_column("guests", "bring_a_plus_one_id")
    # ### end Alembic commands ###
