"""remove foreign key constraints from email_logs

Revision ID: 4065225aa62d
Revises: d254bb00401d
Create Date: 2026-03-09 14:52:14.364596

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '4065225aa62d'
down_revision = 'd254bb00401d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_logs_user_id_fkey'), 'email_logs', type_='foreignkey')
    op.drop_constraint(op.f('email_logs_guest_id_fkey'), 'email_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('email_logs_guest_id_fkey'), 'email_logs', 'guests', ['guest_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('email_logs_user_id_fkey'), 'email_logs', 'users', ['user_id'], ['uuid'], ondelete='SET NULL')
    # ### end Alembic commands ###

