"""add-email-send-on

Revision ID: d6ea7082a6f2
Revises: b2c3d4e5f6a7
Create Date: 2026-02-14 16:20:55.317777

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd6ea7082a6f2'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'guest_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('adult', 'child', name='guest_type_enum'),
               existing_nullable=False)
    op.add_column('rsvp_info', sa.Column('email_sent_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsvp_info', 'email_sent_on')
    op.alter_column('guests', 'guest_type',
               existing_type=sa.Enum('adult', 'child', name='guest_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###

