"""remove enums

Revision ID: cddde675a3a3
Revises: 20c411bf8ce1
Create Date: 2026-03-09 17:15:33.008898

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cddde675a3a3"
down_revision = "20c411bf8ce1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dietary_options",
        "requirement_type",
        existing_type=postgresql.ENUM(
            "VEGETARIAN",
            "VEGAN",
            "GLUTEN_FREE",
            "DAIRY_FREE",
            "HALAL",
            "KOSHER",
            "NUT_ALLERGY",
            "OTHER",
            name="dietary_type_enum",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "email_logs",
        "status",
        existing_type=postgresql.ENUM(
            "pending",
            "sent",
            "delivered",
            "bounced",
            "failed",
            "complained",
            name="email_status_enum",
        ),
        type_=sa.String(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::email_status_enum"),
    )
    op.alter_column(
        "email_logs",
        "language",
        existing_type=postgresql.ENUM("en", "nl", name="language_enum_ref"),
        type_=sa.String(length=2),
        existing_nullable=True,
    )
    op.alter_column(
        "guests",
        "guest_type",
        existing_type=postgresql.ENUM("adult", "child", name="guest_type_enum"),
        type_=sa.String(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "guests",
        "preferred_language",
        existing_type=postgresql.ENUM("en", "es", "nl", name="language_enum"),
        type_=sa.String(length=2),
        existing_nullable=False,
        existing_server_default=sa.text("'en'::language_enum"),
    )
    op.alter_column(
        "rsvp_info",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "CONFIRMED", "DECLINED", name="guest_status_enum_v2"
        ),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rsvp_info",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("PENDING", "CONFIRMED", "DECLINED", name="guest_status_enum_v2"),
        existing_nullable=False,
    )
    op.alter_column(
        "guests",
        "preferred_language",
        existing_type=sa.String(length=2),
        type_=postgresql.ENUM("en", "es", "nl", name="language_enum"),
        existing_nullable=False,
        existing_server_default=sa.text("'en'::language_enum"),
    )
    op.alter_column(
        "guests",
        "guest_type",
        existing_type=sa.String(length=10),
        type_=postgresql.ENUM("adult", "child", name="guest_type_enum"),
        existing_nullable=False,
    )
    op.alter_column(
        "email_logs",
        "language",
        existing_type=sa.String(length=2),
        type_=postgresql.ENUM("en", "nl", name="language_enum_ref"),
        existing_nullable=True,
    )
    op.alter_column(
        "email_logs",
        "status",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM(
            "pending",
            "sent",
            "delivered",
            "bounced",
            "failed",
            "complained",
            name="email_status_enum",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::email_status_enum"),
    )
    op.alter_column(
        "dietary_options",
        "requirement_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "VEGETARIAN",
            "VEGAN",
            "GLUTEN_FREE",
            "DAIRY_FREE",
            "HALAL",
            "KOSHER",
            "NUT_ALLERGY",
            "OTHER",
            name="dietary_type_enum",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
