"""add-email-send-on

Revision ID: d6ea7082a6f2
Revises: b2c3d4e5f6a7
Create Date: 2026-02-14 16:20:55.317777

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6ea7082a6f2"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL with USING clause to cast VARCHAR to enum type
    op.execute(
        "ALTER TABLE guests ALTER COLUMN guest_type TYPE guest_type_enum USING guest_type::guest_type_enum"
    )
    op.add_column(
        "rsvp_info", sa.Column("email_sent_on", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rsvp_info", "email_sent_on")
    # Use raw SQL with USING clause to cast enum back to VARCHAR
    op.execute("ALTER TABLE guests ALTER COLUMN guest_type TYPE VARCHAR(20) USING guest_type::text")
    # ### end Alembic commands ###
