"""convert_email_type_to_varchar

Revision ID: 20c411bf8ce1
Revises: 4065225aa62d
Create Date: 2026-03-09 15:58:05.636784

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "20c411bf8ce1"
down_revision = "4065225aa62d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_logs",
        "email_type",
        existing_type=postgresql.ENUM(
            "invitation",
            "confirmation",
            "reminder",
            "plus_one_invite",
            "forwarded",
            name="email_type_enum",
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email_logs",
        "email_type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "invitation",
            "confirmation",
            "reminder",
            "plus_one_invite",
            "forwarded",
            name="email_type_enum",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
