"""split rsvp into model

Revision ID: 54c8e98ab9ff
Revises: 68bcb874bd92
Create Date: 2026-02-02 07:09:07.243258

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "54c8e98ab9ff"
down_revision = "68bcb874bd92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rsvp_info",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "DECLINED", name="guest_status_enum_v2"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("rsvp_token", sa.String(length=36), nullable=False),
        sa.Column("rsvp_link", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_rsvp_info_guest_id"), "rsvp_info", ["guest_id"], unique=False)
    op.create_index(op.f("ix_rsvp_info_rsvp_token"), "rsvp_info", ["rsvp_token"], unique=True)
    op.drop_index(op.f("ix_guests_rsvp_token"), table_name="guests")
    op.drop_column("guests", "rsvp_token")
    op.drop_column("guests", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guests",
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "CONFIRMED", "DECLINED", name="guest_status_enum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "guests",
        sa.Column("rsvp_token", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_guests_rsvp_token"), "guests", ["rsvp_token"], unique=True)
    op.drop_index(op.f("ix_rsvp_info_rsvp_token"), table_name="rsvp_info")
    op.drop_index(op.f("ix_rsvp_info_guest_id"), table_name="rsvp_info")
    op.drop_table("rsvp_info")
    # ### end Alembic commands ###
