"""init models

Revision ID: 68bcb874bd92
Revises:
Create Date: 2026-02-01 18:03:58.897562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68bcb874bd92"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "guests",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "DECLINED", name="guest_status_enum"),
            nullable=False,
        ),
        sa.Column("is_plus_one", sa.Boolean(), nullable=False),
        sa.Column("plus_one_of_id", sa.Uuid(), nullable=True),
        sa.Column("plus_one_name", sa.String(length=255), nullable=True),
        sa.Column("rsvp_token", sa.String(length=36), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["plus_one_of_id"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_guests_first_name"), "guests", ["first_name"], unique=False)
    op.create_index(op.f("ix_guests_last_name"), "guests", ["last_name"], unique=False)
    op.create_index(op.f("ix_guests_rsvp_token"), "guests", ["rsvp_token"], unique=True)
    op.create_index(op.f("ix_guests_user_id"), "guests", ["user_id"], unique=False)
    op.create_table(
        "dietary_options",
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column(
            "requirement_type",
            sa.Enum(
                "VEGETARIAN",
                "VEGAN",
                "GLUTEN_FREE",
                "DAIRY_FREE",
                "HALAL",
                "KOSHER",
                "NUT_ALLERGY",
                "OTHER",
                name="dietary_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_dietary_options_guest_id"), "dietary_options", ["guest_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dietary_options_guest_id"), table_name="dietary_options")
    op.drop_table("dietary_options")
    op.drop_index(op.f("ix_guests_user_id"), table_name="guests")
    op.drop_index(op.f("ix_guests_rsvp_token"), table_name="guests")
    op.drop_index(op.f("ix_guests_last_name"), table_name="guests")
    op.drop_index(op.f("ix_guests_first_name"), table_name="guests")
    op.drop_table("guests")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
