"""add_needs_transport_to_rsvp_info

Revision ID: d254bb00401d
Revises: cd8837ee4ecd
Create Date: 2026-03-01 19:02:06.708086

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d254bb00401d"
down_revision = "cd8837ee4ecd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transport_guest_id"), table_name="transport")
    op.drop_table("transport")
    # Add column as nullable first, then set default for existing rows
    op.add_column(
        "rsvp_info",
        sa.Column("needs_transport", sa.Boolean(), nullable=True, server_default="false"),
    )
    # Update existing rows to False
    op.execute("UPDATE rsvp_info SET needs_transport = false WHERE needs_transport IS NULL")
    # Alter to NOT NULL
    op.alter_column("rsvp_info", "needs_transport", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rsvp_info", "needs_transport")
    op.create_table(
        "transport",
        sa.Column("guest_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("pickup_location", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["guests.uuid"], name=op.f("transport_guest_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("transport_pkey")),
    )
    op.create_index(op.f("ix_transport_guest_id"), "transport", ["guest_id"], unique=True)
    # ### end Alembic commands ###
