"""add_transport_table

Revision ID: cd8837ee4ecd
Revises: e056202eb20d
Create Date: 2026-03-01 18:21:09.274337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd8837ee4ecd"
down_revision = "e056202eb20d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transport",
        sa.Column("guest_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_location", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_transport_guest_id"), "transport", ["guest_id"], unique=True)
    op.drop_index(op.f("ix_email_logs_created_at"), table_name="email_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_email_logs_created_at"), "email_logs", ["created_at"], unique=False)
    op.drop_index(op.f("ix_transport_guest_id"), table_name="transport")
    op.drop_table("transport")
    # ### end Alembic commands ###
