name: wedding-caddy

on:
  push:
    paths:
      - 'deploy/caddy/**'
      - 'Caddyfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: lowercase-owner
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v7
        with:
          context: ./deploy/caddy
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase-owner.outputs.owner }}/wedding-caddy:c-${{ github.sha }}
            ghcr.io/${{ steps.lowercase-owner.outputs.owner }}/wedding-caddy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
